```{r}
library('lme4')
library('lmerTest')
library("dplyr")
library(tidyverse)
source("Functions.R")
```
````{r}
data<-read.csv("moraldata/imagesmergedtoanalyze.csv")
head(data,5)
```
```{r}
newdata <- data[ which(data$movement != 3 & data$accuracy == 1 
                       & data$accuracy_total >= 0.75 
                       & data$response_time >= 100 ), ]

newdata <- newdata[ which(newdata$response_time <= 2500), ]
```
```{r}
newdata$Implicit_RC <- relevel(as.factor(newdata$ImpVsExp),ref='Explicit')
newdata$Moral_ValenceRC <- relevel(as.factor(newdata$Moral_Valence),ref='Neutral')
newdata$Movement_RC <- relevel(as.factor(newdata$movement),ref='Avoid')
```
```{r}
newdata$BirthGender = as.factor(newdata$BirthGender)
newdata$Race = as.factor(newdata$Race)
newdata = newdata %>%
  mutate(MoralRating_Cat = case_when(MoralRating < 40 ~ "Immoral",
                                     MoralRating >= 40 & MoralRating <=60 ~ "Neutral",
                                     MoralRating > 60 ~ "Moral",
                                     is.na(MoralRating) ~ as.character(Moral_ValenceRC)))
newdata$MoralRating_Cat = relevel(as.factor(newdata$MoralRating_Cat),ref="Neutral")
newdata_implicit = newdata%>%filter(Implicit_RC == "Implicit")
newdata_explicit = newdata%>%filter(Implicit_RC=="Explicit")
```

# EDA

```{r}
# Implicit seems to have faster response time than explicit overall
newdata %>%
  group_by(Implicit_RC)%>%
  ggplot(aes(x=log(response_time),fill=Implicit_RC))+geom_density(alpha=0.5)

# Not much difference in response times for approach/avoid for different moral categories within implicit.
newdata_implicit %>%
  group_by(Movement_RC)%>%
  ggplot(aes(x=log(response_time),fill=Movement_RC))+geom_density(alpha=0.5)+facet_grid(~MoralRating_Cat)

# Wider distributions for response times within the Neutral category for both approach/avoid. Approaching Moral stimuli seems to have a faster and narrower distribution than avoiding.
newdata_explicit %>%
  group_by(Movement_RC)%>%
  ggplot(aes(x=log(response_time),fill=Movement_RC))+geom_density(alpha=0.5)+facet_grid(~MoralRating_Cat)

# Notable differences in response times within explicit
newdata_explicit%>%
  group_by(MoralRating_Cat)%>%
  ggplot(aes(x=MoralRating_Cat,y=log(response_time)))+geom_boxplot()

# Not much difference in response times within implicit
newdata_implicit%>%
  group_by(MoralRating_Cat)%>%
  ggplot(aes(x=MoralRating_Cat,y=log(response_time)))+geom_boxplot()

# White people seem to respond faster
newdata%>%
  filter(Race %in% c(1,5))%>%
  ggplot(aes(x=Race,y=log(response_time)))+geom_boxplot()+scale_x_discrete(labels=c("1" = "Black", "5" = "White"))+xlab("Participant Race")

# Response time seems to increase with age, possibility of containing cluster groups.
newdata%>%
  ggplot(aes(x=Age, y=log(response_time))) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", colour="white")
```

```{r}
set.seed(10)
model_explicit = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=newdata_explicit)
summary(model_explicit)

# Explicit Approach Moral
E_A_Moral= bootstrap_func(target="log(response_time)",ind_var=c("BirthGender","Race","Age","Movement_RC*MoralRating_Cat"),group_var = "participant",dataset = newdata_explicit,coef_interest = c("Movement_RCApproach","MoralRating_CatMoral","Movement_RCApproach:MoralRating_CatMoral"))
exp(E_A_Moral)

# Explicit Approach Immoral
E_A_Immoral = bootstrap_func(target="log(response_time)",ind_var=c("BirthGender","Race","Age","Movement_RC*MoralRating_Cat"),group_var = "participant",dataset = newdata_explicit,coef_interest = c("Movement_RCApproach","MoralRating_CatImmoral","Movement_RCApproach:MoralRating_CatImmoral"))
exp(E_A_Immoral)

# Is approaching Moral significantly faster than approaching immoral?

bootstrap_est = replicate(1000,{
  sample_indices = sample(nrow(newdata_explicit),replace=TRUE)
  sample_data = newdata_explicit[sample_indices,]
  boot_model = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=sample_data)
  comp_effect = summary(boot_model)$coefficients["MoralRating_CatMoral","Estimate"]+summary(boot_model)$coefficients["Movement_RCApproach:MoralRating_CatMoral","Estimate"]-summary(boot_model)$coefficients["MoralRating_CatImmoral","Estimate"]-summary(boot_model)$coefficients["Movement_RCApproach:MoralRating_CatImmoral","Estimate"]
  
  return(comp_effect)
})
composite_effect_mean <- mean(bootstrap_est)
composite_effect_se <- sd(bootstrap_est)
t_value <- composite_effect_mean / composite_effect_se
2 * pt(-abs(t_value), df = length(bootstrap_est) - 1) < 0.05

sorted_estimates <- sort(bootstrap_est)

# Calculate the indices for the 2.5th and 97.5th percentiles
lower_index <- floor(0.025 * length(sorted_estimates))
upper_index <- ceiling(0.975 * length(sorted_estimates))

# Use these indices to find the corresponding values in the sorted list
lower_bound <- sorted_estimates[lower_index]
upper_bound <- sorted_estimates[upper_index]

c(lower_bound,upper_bound)


# Is avoiding immoral significantly faster than avoiding moral?

bootstrap_est = replicate(1000,{
  sample_indices = sample(nrow(newdata_explicit),replace=TRUE)
  sample_data = newdata_explicit[sample_indices,]
  boot_model = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=sample_data)
  comp_effect = summary(boot_model)$coefficients["MoralRating_CatMoral","Estimate"]-summary(boot_model)$coefficients["MoralRating_CatImmoral","Estimate"]
  
  return(comp_effect)
})
composite_effect_mean <- mean(bootstrap_est)
composite_effect_se <- sd(bootstrap_est)
t_value <- composite_effect_mean / composite_effect_se
2 * pt(-abs(t_value), df = length(bootstrap_est) - 1) < 0.05

sorted_estimates <- sort(bootstrap_est)

# Calculate the indices for the 2.5th and 97.5th percentiles
lower_index <- floor(0.025 * length(sorted_estimates))
upper_index <- ceiling(0.975 * length(sorted_estimates))

# Use these indices to find the corresponding values in the sorted list
lower_bound <- sorted_estimates[lower_index]
upper_bound <- sorted_estimates[upper_index]

c(lower_bound,upper_bound)

```

```{r}
model_trial_implicit = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=newdata_implicit)
summary(model_trial_implicit)

# Implicit Approach Moral
I_A_Moral= bootstrap_func(target="log(response_time)",ind_var=c("BirthGender","Race","Age","Movement_RC*MoralRating_Cat"),group_var = "participant",dataset = newdata_implicit,coef_interest = c("Movement_RCApproach","MoralRating_CatMoral","Movement_RCApproach:MoralRating_CatMoral"))
exp(I_A_Moral)


# Implicit Approach Immoral
I_A_Immoral = bootstrap_func(target="log(response_time)",ind_var=c("BirthGender","Race","Age","Movement_RC*MoralRating_Cat"),group_var = "participant",dataset = newdata_implicit,coef_interest = c("Movement_RCApproach","MoralRating_CatImmoral","Movement_RCApproach:MoralRating_CatImmoral"))
exp(I_A_Immoral)

# Is approaching Moral significantly faster than avoiding Moral?

bootstrap_est = replicate(1000,{
  sample_indices = sample(nrow(newdata_implicit),replace=TRUE)
  sample_data = newdata_implicit[sample_indices,]
  boot_model = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=sample_data)
  comp_effect = summary(boot_model)$coefficients["MoralRating_CatMoral","Estimate"]+summary(boot_model)$coefficients["Movement_RCApproach:MoralRating_CatMoral","Estimate"]-summary(boot_model)$coefficients["MoralRating_CatImmoral","Estimate"]-summary(boot_model)$coefficients["Movement_RCApproach:MoralRating_CatImmoral","Estimate"]
  
  return(comp_effect)
})
composite_effect_mean <- mean(bootstrap_est)
composite_effect_se <- sd(bootstrap_est)
t_value <- composite_effect_mean / composite_effect_se
2 * pt(-abs(t_value), df = length(bootstrap_est) - 1) < 0.05

sorted_estimates <- sort(bootstrap_est)

# Calculate the indices for the 2.5th and 97.5th percentiles
lower_index <- floor(0.025 * length(sorted_estimates))
upper_index <- ceiling(0.975 * length(sorted_estimates))

# Use these indices to find the corresponding values in the sorted list
lower_bound <- sorted_estimates[lower_index]
upper_bound <- sorted_estimates[upper_index]

c(lower_bound,upper_bound)


# Is avoiding Moral significantly faster than avoiding Moral?

bootstrap_est = replicate(1000,{
  sample_indices = sample(nrow(newdata_implicit),replace=TRUE)
  sample_data = newdata_implicit[sample_indices,]
  boot_model = lmer(log(response_time)~BirthGender+Race+Age+Movement_RC*MoralRating_Cat+(1|participant),data=sample_data)
  comp_effect = summary(boot_model)$coefficients["MoralRating_CatMoral","Estimate"]-summary(boot_model)$coefficients["MoralRating_CatImmoral","Estimate"]
  
  return(comp_effect)
})
composite_effect_mean <- mean(bootstrap_est)
composite_effect_se <- sd(bootstrap_est)
t_value <- composite_effect_mean / composite_effect_se
2 * pt(-abs(t_value), df = length(bootstrap_est) - 1) < 0.05

sorted_estimates <- sort(bootstrap_est)

# Calculate the indices for the 2.5th and 97.5th percentiles
lower_index <- floor(0.025 * length(sorted_estimates))
upper_index <- ceiling(0.975 * length(sorted_estimates))

# Use these indices to find the corresponding values in the sorted list
lower_bound <- sorted_estimates[lower_index]
upper_bound <- sorted_estimates[upper_index]

c(lower_bound,upper_bound)

```

```{r}

#plots

df_phrases = data.frame(Estimate = c(11.61,7.89,1.26,8.57,8.1,2.70,1.53,2.18,-0.48,-1.1), Moral_Valence = c("Moral","Immoral","Neutral","Moral","Immoral","Moral","Immoral","Neutral","Moral","Immoral"),Movement = c("Approach","Approach","Approach","Avoid","Avoid","Approach","Approach","Approach","Avoid","Avoid"), Lower_Bound = c(10.21,6.47,-0.06,6.98,6.47,1.46,0.032,0.09,-1.78,-2.41),Upper_Bound = c(13,9.38,3.07,10.13,9.7,3.97,2.73,3.46,0.08,0.02),ImpVsExp=c("Explicit","Explicit","Explicit","Explicit","Explicit","Implicit","Implicit","Implicit","Implicit","Implicit"))

df_phrases %>% ggplot(aes(x=Movement,y=Estimate,col=Moral_Valence))+geom_pointrange(aes(ymin = df_phrases$Lower_Bound, ymax = df_phrases$Upper_Bound),position = position_dodge(width = 0.3),size=1.5)+facet_grid(~ImpVsExp)+ylab("Percentage Change (+ values represent faster)")


df_images = data.frame(Estimate = c(10.99,14.79,-0.03,10.81,13.54,3.12,2.07,1.86,1.00,1.03), Moral_Valence = c("Moral","Immoral","Neutral","Moral","Immoral","Moral","Immoral","Neutral","Moral","Immoral"),Movement = c("Approach","Approach","Approach","Avoid","Avoid","Approach","Approach","Approach","Avoid","Avoid"), Lower_Bound = c(9.26,13.05,-2.54,8.89,11.80,1.88,0.07,0.06,-0.03,-0.03), Upper_Bound = c(12.71,16.55,1.89,12.68,15.24,4.36,3.38,3.31,2.33,2.34),ImpVsExp=c("Explicit","Explicit","Explicit","Explicit","Explicit","Implicit","Implicit","Implicit","Implicit","Implicit"))
df_images %>% ggplot(aes(x=Movement,y=Estimate,col=Moral_Valence))+geom_pointrange(aes(ymin = df_images$Lower_Bound, ymax = df_images$Upper_Bound),position = position_dodge(width = 0.3),size=1.5)+facet_grid(~ImpVsExp)+ylab("Percentage Change (+ values represent faster)")
```

